### ISSUE TITLE
Centrally Present Project Rationale

### ISSUE THREAD

**Issue by RandomDSdevel** [portage-brew/portage-brew-staging-and-evolution#11]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Per @joshka's [comment](https://github.com/portage-brew/portage-brew-staging-and-evolution/issues/2#issuecomment-457874364) in #2:  

> A suggestion for [handling interactions between portage-brew and Homebrew upstream]. Don't treat this as a war or an argument that needs to be won about the features that are missing[/]different to how you want them. Treat this more as an experiment to prove that the things that you care about are useful, possible, impactful, etc. Find ways to provide rationale for the things where you differ rather and the open dissent should be acceptable to rational people. An interesting example of this approach I read just today was [Fossil vs Git](https://fossil-scm.org/fossil/doc/trunk/www/fossil-v-git.wiki) on Fossil's wiki. The thing I really liked about this article is that it presented the differences with emapthy for the underlying reasons that lead to Git's choices and doesn't take a stance that Fossil's choices are the only right way. The resulting conversation about this on hackernews was therefore pretty civil compared to had this been a 'Why Fossil is better than Git' type article.

We should cover this in some central location, likely a document in this repository for now.  

CC @portage-brew/maintainers for initial wording proposals, as I have yet to collect enough thoughts to make one of my own.

**Comment by rw** [comment]
IMO we should explain:

+ Why fork? Be concrete and dispassionate.
+ Would we ever end the project? (If Homebrew brought back source builds, for example.)
+ What are we choosing to trade off? (Example: we choose source builds, but we give up build pipelines.)

**Comment by joshka** [comment]
You might also consider:
- what are your constraints. The homebrew project has these. They're the reason why they do what they do and are successful at it.
- will you take on all problems, or constrain them to some of the bigger ones (e.g. dropping options)
