### ISSUE TITLE
Viable MVP?

### ISSUE THREAD

**Issue by rw** [portage-brew/portage-brew-staging-and-evolution#6]
Is it possible to just have a version of the `brew` program that makes it so `pour_bottle?` *always* returns false? It seems like that would solve a lot of our concerns.

**Comment by RandomDSdevel** [comment]
@rw:  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;We're discussing project directions in #2 and #4, but, yes, that's one thing we could do…though I was thinking…_[bigger](https://github.com/portage-brew/brew/issues/1)._

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;You can also create issues/PRs and add them to ~~[portage-brew/brew](https://github.com/portage-brew/brew)'s~~the organization-wide ['Minimum Viable Product' project page](https://github.com/portage-brew/projects/1).  

(Edited to reflect my moving the project board.)
