### ISSUE TITLE
Create Forks for Other Homebrew Tools

### ISSUE THREAD

**Issue by RandomDSdevel** [portage-brew/portage-brew-staging-and-evolution#8]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I've already created this organization's main '`brew`' tooling implementation repository fork, but we'll also need forks of at least:  

- [Homebrw/install](https://github.com/Homebrew/install)
- [Homebrew/homebrw-core](https://github.com/Homebrew/homebrew-core)
- [Homebrew/homebrew-test-bot](https://github.com/Homebrew/homebrew-test-bot) (For CI, which we'll undoubtedly want.)  
- [Homebrew/brew.sh](https://github.com/Homebrew/brew.sh)
- [Homebrew/formulae.brew.sh](https://github.com/Homebrew/formulae.brew.sh)

I'm leaving this here as a reminder to take care of setting our downstream equivalents of these up.

**Comment by RandomDSdevel** [comment]
@jkulesza:  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;You can merge the tap you create in order to address your issue with Homebrew/homebrew-core#35236 into portage-brew's homebrew-core fork once it's live, if you like.  I was never able to get  Homebrew/homebrew-core#31510 resolved to my satisfaction, as it proved…rather difficult to debug, to say the least, and any work done toward restoring old options to formulas is welcomed here!

**Comment by blogabe** [comment]
A recent change homebrew introduced is that even if you build a formula from source, the relevant dependencies will still be bottles.  This is a problem in my opinion if the whole point of this project is to continue building from source and offering options.

The way around this is to `brew deps -n --include-build --include-requirements <formula> <options>` and install those dependencies from source.  For example:
```
brew install --build-from-source `brew deps -n --include-build --include-requirements blogabe/xplanet/xplanetfx --with-gnu-sed --with-gui | grep -v ':macOS'` && brew install --build-from-source blogabe/xplanet/xplanetfx --with-gnu-sed --with-gui
```

There was another recent change today, https://github.com/Homebrew/brew/commit/7b6d1f774d62b5f68326257dc43bb1cfad155c24, that breaks the above workaround and ignores the formula's options.  Speaking with Mike about resolving the issue so that we can still build dependencies from source.  As of right now, however, all dependencies are back to being bottles.

**Comment by RandomDSdevel** [comment]
@blogabe:  See https://github.com/portage-brew/portage-brew-staging-and-evolution/issues/4#issuecomment-457437696.

**Comment by chdiza** [comment]
I would like to know why I keep receiving emails from GitHub about this repo.  I didn't accept any invitation, and in this very thread (e.g.) I haven't been mentioned nor have I participated (until this very post).

**Comment by RandomDSdevel** [comment]
@chdiza:  

> I would like to know why I keep receiving emails from GitHub about this repo. …[I]n this very thread (e.g.) I haven't been mentioned nor have I participated (until this very post).

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Huh, odd.  No idea.  That's…a good question.  

> …I didn't accept any invitation, …

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The one you've been extended already's still open, though I understand if you feel doing so would create a conflict of interest with upstream.

**Comment by chdiza** [comment]
I don't see a button on GitHub for declining an invitation.

I do appreciate the invite, but I've already made my own "fork" of HB back in October, and I barely have time to work on *that*, let alone contribute to *two* forks.

**Comment by RandomDSdevel** [comment]
@chdiza:  

> I don't see a button on GitHub for declining an invitation.
>
> I do appreciate the invite, but I've already made my own "fork" of HB back in October, …

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;OK, I've canceled your invitation.  As for your fork, you went into more detail on that in [your comment](https://github.com/portage-brew/portage-brew-staging-and-evolution/issues/4#issuecomment-457609331) on #4.  

> …and I barely have time to work on that, let alone contribute to two forks.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Understood.
